CC = gcc
name = SDL_geometry
TARGET = ../bin/$(name)
DEPEND = .depend
LIBS=-lGL -lGLU -lSDL -lglut -ljpeg
LDFLAGS =`sdl-config --libs` -L/usr/X11R6/lib $(LIBS)
CFLAGS = `sdl-config --cflags` -Wall -O2
OBJ = ./tools/textglut.o ./tools/texture.o ./tools/image_lib.o ./tools/object3d.o
 
.c.o:
	$(CC) $(CFLAGS) -Wall -O2 -c -o $@ $<

$(TARGET): $(name).o $(OBJ)
	$(CC) $(LDFLAGS) $^ -o  $@
	rm  -R -f  *.o
	rm  -R -f  ./tools/*.o


clean:
	rm  -R -f  *.o
